# encoding: UTF-8

if(City.all.length == 0)
  City.create(name:"Айтос") 
  City.create(name:"Аксаково") 
  City.create(name:"Алфатар") 
  City.create(name:"Антоново") 
  City.create(name:"Априлци") 
  City.create(name:"Ардино") 
  City.create(name:"Асеновград") 
  City.create(name:"Ахелой (град)") 
  City.create(name:"Ахтопол") 
  City.create(name:"Балчик") 
  City.create(name:"Банкя") 
  City.create(name:"Банско") 
  City.create(name:"Баня (град)") 
  City.create(name:"Батак") 
  City.create(name:"Батановци") 
  City.create(name:"Белене") 
  City.create(name:"Белица") 
  City.create(name:"Белово") 
  City.create(name:"Белоградчик") 
  City.create(name:"Белослав") 
  City.create(name:"Берковица") 
  City.create(name:"Благоевград") 
  City.create(name:"Бобов дол") 
  City.create(name:"Бобошево") 
  City.create(name:"Божурище") 
  City.create(name:"Бойчиновци") 
  City.create(name:"Болярово") 
  City.create(name:"Борово") 
  City.create(name:"Ботевград") 
  City.create(name:"Брацигово") 
  City.create(name:"Брегово") 
  City.create(name:"Брезник") 
  City.create(name:"Брезово") 
  City.create(name:"Брусарци") 
  City.create(name:"Бургас") 
  City.create(name:"Бухово") 
  City.create(name:"Българово") 
  City.create(name:"Бяла (Област Варна)") 
  City.create(name:"Бяла (Област Русе)") 
  City.create(name:"Бяла Слатина") 
  City.create(name:"Варна") 
  City.create(name:"Велики Преслав") 
  City.create(name:"Велико Търново") 
  City.create(name:"Велинград") 
  City.create(name:"Ветово") 
  City.create(name:"Ветрен (град)") 
  City.create(name:"Видин") 
  City.create(name:"Враца") 
  City.create(name:"Вълчедръм") 
  City.create(name:"Вълчи дол") 
  City.create(name:"Върбица") 
  City.create(name:"Вършец") 
  City.create(name:"Габрово") 
  City.create(name:"Генерал Тошево") 
  City.create(name:"Главиница") 
  City.create(name:"Глоджево") 
  City.create(name:"Годеч") 
  City.create(name:"Горна Оряховица") 
  City.create(name:"Гоце Делчев (град)") 
  City.create(name:"Грамада") 
  City.create(name:"Гулянци") 
  City.create(name:"Гурково") 
  City.create(name:"Гълъбово") 
  City.create(name:"Две могили") 
  City.create(name:"Дебелец") 
  City.create(name:"Девин") 
  City.create(name:"Девня") 
  City.create(name:"Джебел") 
  City.create(name:"Димитровград") 
  City.create(name:"Димово") 
  City.create(name:"Добринище") 
  City.create(name:"Добрич") 
  City.create(name:"Долна баня") 
  City.create(name:"Долна Митрополия") 
  City.create(name:"Долна Оряховица") 
  City.create(name:"Долни Дъбник") 
  City.create(name:"Долни чифлик") 
  City.create(name:"Доспат") 
  City.create(name:"Драгоман") 
  City.create(name:"Дряново") 
  City.create(name:"Дулово") 
  City.create(name:"Дунавци") 
  City.create(name:"Дупница") 
  City.create(name:"Дългопол") 
  City.create(name:"Елена") 
  City.create(name:"Елин Пелин (град)") 
  City.create(name:"Елхово") 
  City.create(name:"Етрополе") 
  City.create(name:"Завет (град)") 
  City.create(name:"Земен") 
  City.create(name:"Златарица") 
  City.create(name:"Златица") 
  City.create(name:"Златоград") 
  City.create(name:"Ивайловград") 
  City.create(name:"Игнатиево") 
  City.create(name:"Искър (град)") 
  City.create(name:"Исперих") 
  City.create(name:"Ихтиман") 
  City.create(name:"Каблешково") 
  City.create(name:"Каварна") 
  City.create(name:"Казанлък") 
  City.create(name:"Калофер") 
  City.create(name:"Камено") 
  City.create(name:"Каолиново") 
  City.create(name:"Карлово") 
  City.create(name:"Карнобат") 
  City.create(name:"Каспичан") 
  City.create(name:"Кермен") 
  City.create(name:"Килифарево") 
  City.create(name:"Клисура") 
  City.create(name:"Кнежа") 
  City.create(name:"Козлодуй") 
  City.create(name:"Койнаре") 
  City.create(name:"Копривщица") 
  City.create(name:"Костандово") 
  City.create(name:"Костенец") 
  City.create(name:"Костинброд") 
  City.create(name:"Котел") 
  City.create(name:"Кочериново") 
  City.create(name:"Кресна") 
  City.create(name:"Криводол") 
  City.create(name:"Кричим") 
  City.create(name:"Крумовград") 
  City.create(name:"Крън") 
  City.create(name:"Кубрат (град)") 
  City.create(name:"Куклен") 
  City.create(name:"Кула (град)") 
  City.create(name:"Кърджали") 
  City.create(name:"Кюстендил") 
  City.create(name:"Левски (град)") 
  City.create(name:"Летница") 
  City.create(name:"Ловеч") 
  City.create(name:"Лозница (град)") 
  City.create(name:"Лом") 
  City.create(name:"Луковит") 
  City.create(name:"Лъки") 
  City.create(name:"Любимец") 
  City.create(name:"Лясковец") 
  City.create(name:"Мадан") 
  City.create(name:"Маджарово") 
  City.create(name:"Малко Търново") 
  City.create(name:"Мартен") 
  City.create(name:"Мездра") 
  City.create(name:"Мелник") 
  City.create(name:"Меричлери") 
  City.create(name:"Мизия (град)") 
  City.create(name:"Момин проход") 
  City.create(name:"Момчилград") 
  City.create(name:"Монтана") 
  City.create(name:"Мъглиж") 
  City.create(name:"Неделино") 
  City.create(name:"Несебър") 
  City.create(name:"Николаево") 
  City.create(name:"Никопол") 
  City.create(name:"Нова Загора") 
  City.create(name:"Нови Искър") 
  City.create(name:"Нови пазар") 
  City.create(name:"Обзор") 
  City.create(name:"Омуртаг (град)") 
  City.create(name:"Опака") 
  City.create(name:"Оряхово") 
  City.create(name:"Павел баня") 
  City.create(name:"Павликени") 
  City.create(name:"Пазарджик") 
  City.create(name:"Панагюрище") 
  City.create(name:"Перник") 
  City.create(name:"Перущица") 
  City.create(name:"Петрич") 
  City.create(name:"Пещера (град)") 
  City.create(name:"Пирдоп") 
  City.create(name:"Плачковци") 
  City.create(name:"Плевен") 
  City.create(name:"Плиска") 
  City.create(name:"Пловдив") 
  City.create(name:"Полски Тръмбеш") 
  City.create(name:"Поморие") 
  City.create(name:"Попово") 
  City.create(name:"Пордим") 
  City.create(name:"Правец") 
  City.create(name:"Приморско") 
  City.create(name:"Провадия") 
  City.create(name:"Първомай") 
  City.create(name:"Раднево") 
  City.create(name:"Радомир") 
  City.create(name:"Разград") 
  City.create(name:"Разлог") 
  City.create(name:"Ракитово") 
  City.create(name:"Раковски (град)") 
  City.create(name:"Рила (град)") 
  City.create(name:"Роман (България)") 
  City.create(name:"Рудозем") 
  City.create(name:"Русе") 
  City.create(name:"Садово") 
  City.create(name:"Самоков") 
  City.create(name:"Сандански") 
  City.create(name:"Сапарева баня") 
  City.create(name:"Свети Влас") 
  City.create(name:"Свиленград") 
  City.create(name:"Свищов") 
  City.create(name:"Своге") 
  City.create(name:"Севлиево") 
  City.create(name:"Сеново") 
  City.create(name:"Септември (град)") 
  City.create(name:"Силистра") 
  City.create(name:"Симеоновград") 
  City.create(name:"Симитли") 
  City.create(name:"Славяново") 
  City.create(name:"Сливен") 
  City.create(name:"Сливница") 
  City.create(name:"Сливо поле") 
  City.create(name:"Смолян") 
  City.create(name:"Смядово") 
  City.create(name:"Созопол") 
  City.create(name:"Сопот") 
  City.create(name:"София") 
  City.create(name:"Средец (град)") 
  City.create(name:"Стамболийски (град)") 
  City.create(name:"Стара Загора") 
  City.create(name:"Стражица") 
  City.create(name:"Стралджа") 
  City.create(name:"Стрелча") 
  City.create(name:"Суворово") 
  City.create(name:"Сунгурларе") 
  City.create(name:"Сухиндол") 
  City.create(name:"Съединение (град)") 
  City.create(name:"Сърница") 
  City.create(name:"Твърдица") 
  City.create(name:"Тервел (град)") 
  City.create(name:"Тетевен") 
  City.create(name:"Тополовград") 
  City.create(name:"Троян") 
  City.create(name:"Трън") 
  City.create(name:"Тръстеник") 
  City.create(name:"Трявна") 
  City.create(name:"Тутракан") 
  City.create(name:"Търговище") 
  City.create(name:"Угърчин") 
  City.create(name:"Хаджидимово") 
  City.create(name:"Харманли") 
  City.create(name:"Хасково") 
  City.create(name:"Хисаря") 
  City.create(name:"Цар Калоян (град)") 
  City.create(name:"Царево") 
  City.create(name:"Чепеларе") 
  City.create(name:"Червен бряг") 
  City.create(name:"Черноморец") 
  City.create(name:"Чипровци") 
  City.create(name:"Чирпан") 
  City.create(name:"Шабла") 
  City.create(name:"Шивачево") 
  City.create(name:"Шипка (град)") 
  City.create(name:"Шумен") 
  City.create(name:"Ябланица") 
  City.create(name:"Якоруда") 
  City.create(name:"Ямбол") 
end